name = "lmpify3"
compatibility_date = "2025-04-21"
dev.port = 3000
main = "main.ts"
assets = { directory = "./", binding = "ASSETS" }
routes = [ 
  { pattern = "letmeprompt.com", custom_domain = true },
  { pattern = "www.letmeprompt.com", custom_domain = true }
]

kv_namespaces = [
  { binding = "RESULTS", id = "e698f458a5c0411b8998f335bd24dc11" }
]

[[durable_objects.bindings]]
name = "DORM_NAMESPACE"
class_name = "DORM"


[[durable_objects.bindings]]
name = "SQL_STREAM_PROMPT_DO"
class_name = "SQLStreamPromptDO"

[[durable_objects.bindings]]
name = "RATELIMIT_DO"
class_name = "RatelimitDO"


[[migrations]]
tag = "v1"
new_sqlite_classes = ["DORM", "StreamPromptDO"]

[[migrations]]
tag = "v3"
deleted_classes = ["StreamPromptDO"]
new_sqlite_classes = ["SQLStreamPromptDO"]

[[migrations]]
tag = "v4"
new_sqlite_classes = ["RatelimitDO"]
